networks:
  bm42:
    name: bm42
    driver: bridge

services:

  bm42:
    image: hack-backend
    build:
      context: ./backend
      target: builder
    container_name: bm42
    networks:
      - bm42
    env_file:
      - .env
    environment:
      PORT: 80
      MAX_WORKERS: 1
    ports:
      - '80:80'
      - '5678:5678'
    volumes:
      - ./backend:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]